version: '3'

services:
  php:
    image: lafony-php:latest
    build:
      context: ./docker/php
    volumes:
      - ./:/var/www/laravel/
    networks:
      - app_network

  nginx:
    image: lafony-nginx:latest
    build:
      context: ./docker/nginx
    volumes:
      - ./:/var/www/laravel/
    ports:
      - "9001:80"
    networks:
      - app_network

  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: noPassword
      MYSQL_DATABASE: lafony
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app_network

volumes:
  db-data:

networks:
  app_network: