version: '3'

services:
  php:
    image: ghcr.io/jagfx/lafony-php:ci
    build:
      context: ./docker/php
    volumes:
      - ./:/var/www/laravel/
    networks:
      - app_network

  nginx:
    image: ghcr.io/jagfx/lafony-nginx:ci
    build:
      context: ./docker/nginx
    volumes:
      - ./:/var/www/laravel/
    ports:
      - "9001:80"
    networks:
      - app_network

  db:
    image: ghcr.io/jagfx/lafony-mysql:ci
    build:
      context: ./docker/mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: noPassword
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app_network

volumes:
  db-data:

networks:
  app_network: