name: CI / CD

on:
  push:
  pull_request:

jobs:
  install:
    name: Install
    runs-on: ubuntu-latest
#    strategy:
#      matrix:
#        node-version: [ 18.x ]
    container:
      image: ghcr.io/jagfx/lafony-php:ci
    steps:
      -   name: Checkout repository
          uses: actions/checkout@v3
          with:
            fetch-depth: 2
#      -   run: git checkout HEAD^2
#          if: ${{ github.event_name == 'pull_request' }}
#      -   name: Configure environment
#          run: make env
      -   name: Read .nvmrc
          run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"
          id: nvm
      -   name: Use Node.js (.nvmrc)
          uses: actions/setup-node@v1
          with:
            node-version: "${{ steps.nvm.outputs.NVMRC }}"
#          script: |
#            export NVM_DIR=~/.nvm
#            source ~/.nvm/nvm.sh
#            npm --help
#          with:
#            node-version: ${{ matrix.node-version }}
      -   name: Install composer dependencies
          run: composer install
      -   name: Install nodejs dependencies
          run: npm i
      -   name: Cache dependencies
          uses: actions/cache@v3
          id: restore-build
          with:
            path: ./*
            key: ${{ github.sha }}

  linter:
    name: Linter
    runs-on: ubuntu-latest
    needs: [install]
    container:
      image: ghcr.io/jagfx/lafony-php:ci
    steps:
      -   name: Checkout repository
          uses: actions/checkout@v3
          with:
            fetch-depth: 2
#      -   name: Use Node.js ${{ matrix.node-version }}
#          uses: actions/setup-node@v3
#          with:
#            node-version: ${{ matrix.node-version }}
      -   uses: actions/cache@v3
          id: restore-build
          with:
            path: ./*
            key: ${{ github.sha }}
      -   name: Run Laravel pint
          run: php vendor/bin/pint -v
      -   name: Run PHPStan
          run: php vendor/bin/phpstan analyse
      -   name: Run Rector
          run: php vendor/bin/rector process --xdebug

  unit_test:
    name: Unit test
    runs-on: ubuntu-latest
    needs: [install]
    container:
      image: ghcr.io/jagfx/lafony-php:ci
    steps:
      -   name: Checkout repository
          uses: actions/checkout@v3
          with:
            fetch-depth: 2
#      -   name: Use Node.js ${{ matrix.node-version }}
#          uses: actions/setup-node@v3
#          with:
#            node-version: ${{ matrix.node-version }}
      -   uses: actions/cache@v3
          id: restore-build
          with:
            path: ./*
            key: ${{ github.sha }}
      -   name: Run unit test
          run: php vendor/bin/phpunit tests/Unit